### ISSUE TITLE
vim-galore 中文翻译项目邀请您一起参与

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/vim-galore-zh_cn#1]
vim-galore 是一个非常不错的vim教程，目前准备给他做中文翻译，希望有兴趣的朋友可以一起帮核对一下，谢谢！

原文地址: https://github.com/mhinz/vim-galore

基于[mhinz/vim-galore@d50d48b](https://github.com/mhinz/vim-galore/tree/d50d48bce40bbbd99a0528a2893b00cf54a6f4b9), 后期如果有改动，定期在更新。

如果有兴趣加入的，可以 @ 我。

**Comment by kdurant** [comment]
我可以

**Comment by wsdjeg** [comment]
@mhinz

thanks for your work. we are going to make a chinese version, many people will join us. if the work is done, would you please add a link to your readme. or can you help me to twitter this repo.

**Comment by FineFan** [comment]
Please let me in .

**Comment by S1ngS1ng** [comment]
I am in

**Comment by mudongliang** [comment]
@wsdjeg Join in.

**Comment by GHLandy** [comment]
+1，不过好像都没有开始呢？@wsdjeg

**Comment by holidaying** [comment]
算我一个

**Comment by skyseraph** [comment]
+1

**Comment by gradyu** [comment]
+1

**Comment by mhinz** [comment]
Woah, this is great. Thanks for the effort! 👍 

> would you please add a link to your readme

Of course I will! It doesn't have to be finished. The Portuguese translation is work-in-progress as well. When the first bits are done, I'll gladly link this repo.

**Comment by Togal** [comment]
@wsdjeg +1

**Comment by shixinzhang** [comment]
@wsdjeg +1

**Comment by ZhangFe** [comment]
@wsdjeg +1

**Comment by edvardHua** [comment]
@wsdjeg +1

**Comment by steinliber** [comment]
+1 咯 @wsdjeg

**Comment by xiaoyusilen** [comment]
@wsdjeg +1

**Comment by wsdjeg** [comment]
感谢大家支持，目前首要做的事情，是将原来的英文项目按照章节分别列出，然后，大家可以根据自己的时间安排，认领其中部分章节进行翻译，避免大家的重复劳动。

另外关于合作方式，大家可以 fork 本项目，然后提交PR.

翻译文件放在何处？
1. 我会将原英文进行拆分，列出一系列的文件名称，认领后按照该文件名提交PR， 我会将他合并到主文件。

关于翻译核对，欢迎任何人协助核对，发现PR有问题，或者项目翻译有问题，可以提交issue 或者在 PR 提交 review 。

**Comment by wsdjeg** [comment]
我曾经给这个项目做过部分的翻译，需要先合并一部分这里的翻译。 

https://github.com/wsdjeg/vim-galore

**Comment by wsdjeg** [comment]
anyone can help me review #4

**Comment by KnightCS** [comment]
@wsdjeg +1

**Comment by yuzexia** [comment]
算我一个吧😄

**Comment by YDWX** [comment]
join @wsdjeg

**Comment by wsdjeg** [comment]
谢谢大家支持，需要参与的朋友，可以在 [CONTRIBUTING.md](https://github.com/wsdjeg/vim-galore-zh_cn/blob/master/CONTRIBUTING.md) 中选择先要翻译的章节，并告知我，这样我可以标记上，避免重复翻译。

**Comment by wsdjeg** [comment]
新的问题在 #29 ，打算更新这个项目，欢迎大家加入。
