### ISSUE TITLE
Miscellaneous>>杂项|Common problems>>常规问题

### ISSUE THREAD

**Issue by Laotree** [wsdjeg/vim-galore-zh_cn#11]
章节名称：杂项（Miscellaneous）常规问题（ Common problems）
译者：Laotree
PR: [](url)
2017.04.01前pull

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/vim-galore-zh_cn/pull/10

可以想这样编辑下吗，看不出来是哪几个章节呢

**Comment by wsdjeg** [comment]
收到😜

**Comment by Laotree** [comment]
@wsdjeg 我把杂项里的additional resource翻译了一下，你看合不合格？如果可以我就接着翻下去了。
[additional resource](https://github.com/Laotree/vim-galore-zh_cn/blob/master/chapter/additional-resources.md)

**Comment by wsdjeg** [comment]
可以的，不错😊

**Comment by wsdjeg** [comment]
@Laotree Common problems 在 #18 中已经有人翻译了。

**Comment by Laotree** [comment]
@wsdjeg 看到了，[#18](https://github.com/wsdjeg/vim-galore-zh_cn/pull/18) 翻译的很好，那我的工作也算完成了。谢谢让我参与其中。
