### ISSUE TITLE
文章中的下划线疑问

### ISSUE THREAD

**Issue by einverne** [wsdjeg/vim-galore-zh_cn#27]
看到译文中出现很多 `_` ，是想要表达斜体吗？

GitHub 看来并不识别下划线的语法。

**Comment by wsdjeg** [comment]
恩，具体是哪里？

**Comment by einverne** [comment]
比如这句话 `之后你要用一个_动作_来指定需要操作的文本区域` 动作二字是想要表达斜体吗？

**Comment by wsdjeg** [comment]
是的，这有问题吗？

测试_斜体_字

**Comment by einverne** [comment]
问题就是斜体好像 GitHub 需要用空格隔开？  *这样子* ?

![screenshot from 2017-10-26 10-37-08](https://user-images.githubusercontent.com/1962738/32032433-c6b0fe84-ba39-11e7-9855-4f45ea17d553.png)

**Comment by wsdjeg** [comment]
测试__斜体__

**Comment by wsdjeg** [comment]
是的， 需要这样： `测试 _斜体_ 字`
