### ISSUE TITLE
有一些格式跟編碼的問題

### ISSUE THREAD

**Issue by aguai** [wsdjeg/vim-galore-zh_cn#28]
cd chapter && chmod -x * && declare -a temp=(); for i in *md; chardetect $i |grep -iq 'GB' && temp+=$i; for j in $temp ; iconv -f GBK -t UTF8 $j >tmp && cat tmp > $j ; unset temp ;rm tmp

因為我已經 fork 成繁體中文了 
沒辦法發 full request
勞駕您手動改一下
親測有效

**Comment by wsdjeg** [comment]
感谢，不过我执行后，提示：

```
bash: syntax error near unexpected token `chardetect'

```
