### ISSUE TITLE
Vim Windows下载失效

### ISSUE THREAD

**Issue by shliang0603** [wsdjeg/vim-galore-zh_cn#32]
![image](https://user-images.githubusercontent.com/37186266/51086196-77847b80-177e-11e9-92fa-7fc766a42e2d.png)

你好博主，windows版vim网盘下载链接失效了，麻烦你可以再从新分享一下吗，谢谢啦

**Comment by tstts** [comment]
https://www.vim.org/download.php

**Comment by shliang0603** [comment]
@tstts Thanks for your help
