### ISSUE TITLE
添加部分技巧

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/vim-galore-zh_cn#39]
最近在 v2ex 上看到有人分享一篇不错的 vim 技巧。

https://jdhao.github.io/2019/03/28/nifty_nvim_techniques_s1/

感谢原作者分享，部分内容我将翻译并添加到该项目内，同时在底部添加引用来源，期待下一篇文章。

**Comment by ListenLove** [comment]
收获最大的就是教会了我用_Surround_
