### ISSUE TITLE
中文语法检查脚本

### ISSUE THREAD

**Issue by wsdjeg** [wsdjeg/vim-galore-zh_cn#8]
很多排版规范细微差别，很难手动检查出来，我们需要一个自动检查的脚本，可以对PR进行自动检查。

**Comment by wsdjeg** [comment]
目前已知的 md文档检查工具有：

https://github.com/igorshubovych/markdownlint-cli
https://github.com/mivok/markdownlint
https://github.com/amperser/proselint/
https://github.com/btford/write-good

但这些对中文支持状态还不清楚，需要筛选下。

**Comment by S1ngS1ng** [comment]
我自己有在写一个。。不过暂时还没 public。因为不少问题都没解决，而且也没有完成封装。
目前能实现的功能有：
- 段首不出现符号的检测，以及段尾含有符号的检测
- 中文符号两边无空格的检测
- 句号应在括号外的检测
- 英文标点后的空格检测，以及一些英文标点前的空格检测
- 只允许半角数字和半角英文的检测
- 千分号建议
- 段落间空行的检测

**Comment by wsdjeg** [comment]
我已经开始在写，vim的插件。

**Comment by wsdjeg** [comment]
可以看下 #9

**Comment by S1ngS1ng** [comment]
@wsdjeg 讲真，看不太懂 😞。。VimL 还是不够熟。。
用 JS 的有一个好处，在 Heroku 之类的平台上搭以下，或者用 TravisCI，这样每次开 PR 或者新 commit 都会 trigger 语法检查

**Comment by wsdjeg** [comment]
我明白，我做这个是为了方便本地检查，跳转，比如 我随便写一个文档 检测结果如图：
这就像语法检查插件一样工作。
![2017-03-25_1357x724](https://cloud.githubusercontent.com/assets/13142418/24319832/ac1f2e4a-1162-11e7-8b16-fe8ea59bcbb2.png)

**Comment by wsdjeg** [comment]
目前已经实现的检测有：
- [x] E001 中文之后存在英文标点
- [x] E002 中文和英文之间没有空格
- [x] E003 中文和数字之间没有空格
- [x] E004 中文标点之后存在空格

我需要像merge这个工具了，方便我在其他分支使用。
